# Generated by Django 4.0.3 on 2022-04-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_person_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.IntegerField(default=1234567890),
        ),
    ]
