# Generated by Django 4.0.3 on 2022-04-10 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_person_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
    ]
